export const APP_EDGE_SWIPE_TRIGGER_PX = 28;
export const APP_EDGE_SWIPE_DISTANCE_PX = 72;
export const APP_EDGE_SWIPE_VERTICAL_TOLERANCE_PX = 56;

export const IMAGE_SWIPE_THRESHOLD_PX = 56;
export const IMAGE_SWIPE_VERTICAL_TOLERANCE_PX = 48;
export const IMAGE_DOUBLE_TAP_DELAY_MS = 260;
export const IMAGE_DISMISS_SWIPE_THRESHOLD_PX = 120;

export const MODAL_DISMISS_SWIPE_THRESHOLD_PX = 110;
export const MODAL_DISMISS_VERTICAL_TOLERANCE_PX = 48;

export const PULL_TO_REFRESH_TRIGGER_PX = 84;
export const PULL_TO_REFRESH_MAX_PULL_PX = 128;
