begin;

create table if not exists public.privileged_audit_events (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  constraint privileged_audit_events_safe_metadata check (
    metadata - array['status', 'requested_role', 'old_role', 'new_role', 'old_status', 'new_status', 'role', 'submission_type', 'sent', 'active'] = '{}'::jsonb
  )
);

create index if not exists idx_privileged_audit_events_created_at
  on public.privileged_audit_events (created_at desc, id desc);

alter table public.privileged_audit_events enable row level security;
revoke insert, update, delete on public.privileged_audit_events from anon, authenticated;

drop policy if exists "privileged_audit_events_staff_read" on public.privileged_audit_events;
create policy "privileged_audit_events_staff_read"
on public.privileged_audit_events
for select
to authenticated
using (public.current_user_has_any_role(array['admin', 'moderator', 'training_officer']));

create or replace function public.record_privileged_audit_event(
  p_action text,
  p_target_type text,
  p_target_id text,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.privileged_audit_events (actor_id, action, target_type, target_id, metadata)
  values (auth.uid(), p_action, p_target_type, nullif(p_target_id, ''), coalesce(p_metadata, '{}'::jsonb));
end;
$$;

revoke all on function public.record_privileged_audit_event(text, text, text, jsonb) from public, anon, authenticated;

create or replace function public.audit_access_request_review()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status is distinct from old.status and new.status in ('approved', 'rejected') then
    perform public.record_privileged_audit_event(
      'access_request_' || new.status,
      'account_access_request',
      new.id::text,
      jsonb_build_object('status', new.status, 'requested_role', new.requested_role)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_audit_access_request_review on public.account_access_requests;
create trigger trg_audit_access_request_review
after update of status on public.account_access_requests
for each row execute function public.audit_access_request_review();

create or replace function public.audit_profile_role_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.role is distinct from old.role then
    perform public.record_privileged_audit_event(
      'primary_role_changed',
      'profile',
      new.id::text,
      jsonb_build_object('old_role', old.role, 'new_role', new.role)
    );
  end if;

  if (to_jsonb(new) ->> 'account_status') is distinct from (to_jsonb(old) ->> 'account_status') then
    perform public.record_privileged_audit_event(
      'account_status_changed',
      'profile',
      new.id::text,
      jsonb_build_object(
        'old_status', to_jsonb(old) ->> 'account_status',
        'new_status', to_jsonb(new) ->> 'account_status'
      )
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_audit_profile_role_change on public.profiles;
create trigger trg_audit_profile_role_change
after update on public.profiles
for each row execute function public.audit_profile_role_change();

create or replace function public.audit_user_role_assignment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  affected_user_id uuid;
  affected_role text;
begin
  if tg_op = 'INSERT' then
    affected_user_id := new.user_id;
    affected_role := new.role;
  else
    affected_user_id := old.user_id;
    affected_role := old.role;
  end if;

  perform public.record_privileged_audit_event(
    case when tg_op = 'INSERT' then 'role_assigned' else 'role_removed' end,
    'profile',
    affected_user_id::text,
    jsonb_build_object('role', affected_role)
  );
  if tg_op = 'INSERT' then
    return new;
  end if;
  return old;
end;
$$;

drop trigger if exists trg_audit_user_role_assignment on public.user_roles;
create trigger trg_audit_user_role_assignment
after insert or delete on public.user_roles
for each row execute function public.audit_user_role_assignment();

create or replace function public.audit_case_delete()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.record_privileged_audit_event(
    'case_deleted',
    'case',
    old.id::text,
    jsonb_build_object('status', old.status, 'submission_type', old.submission_type)
  );
  return old;
end;
$$;

drop trigger if exists trg_audit_case_delete on public.cases;
create trigger trg_audit_case_delete
before delete on public.cases
for each row execute function public.audit_case_delete();

create or replace function public.audit_case_viber_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.viber_shared_at is distinct from old.viber_shared_at then
    perform public.record_privileged_audit_event(
      case when new.viber_shared_at is null then 'viber_marked_not_sent' else 'viber_marked_sent' end,
      'case',
      new.id::text,
      jsonb_build_object('sent', new.viber_shared_at is not null)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_audit_case_viber_status on public.cases;
create trigger trg_audit_case_viber_status
after update of viber_shared_at on public.cases
for each row execute function public.audit_case_viber_status();

create or replace function public.audit_case_share_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  audit_action text;
begin
  if tg_op = 'INSERT' then
    audit_action := 'case_share_created';
  elsif new.is_active = false and old.is_active = true then
    audit_action := 'case_share_revoked';
  elsif new.public_token is distinct from old.public_token then
    audit_action := 'case_share_regenerated';
  elsif new.is_active = true and old.is_active = false then
    audit_action := 'case_share_created';
  else
    return new;
  end if;

  perform public.record_privileged_audit_event(
    audit_action,
    'case',
    new.case_id::text,
    jsonb_build_object('active', new.is_active)
  );
  return new;
end;
$$;

drop trigger if exists trg_audit_case_share_change on public.case_shares;
create trigger trg_audit_case_share_change
after insert or update on public.case_shares
for each row execute function public.audit_case_share_change();

create or replace function public.list_privileged_audit_events(
  p_limit integer default 30,
  p_before timestamptz default null
)
returns table (
  id bigint,
  actor_id uuid,
  actor_name text,
  action text,
  target_type text,
  target_id text,
  metadata jsonb,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
stable
as $$
begin
  if not public.current_user_has_any_role(array['admin', 'moderator', 'training_officer']) then
    raise exception 'Only authorized staff can view audit events.';
  end if;

  return query
  select
    events.id,
    events.actor_id,
    coalesce(profiles.nickname, profiles.full_name, 'System') as actor_name,
    events.action,
    events.target_type,
    events.target_id,
    events.metadata,
    events.created_at
  from public.privileged_audit_events events
  left join public.profiles profiles on profiles.id = events.actor_id
  where p_before is null or events.created_at < p_before
  order by events.created_at desc, events.id desc
  limit least(greatest(coalesce(p_limit, 30), 1), 100);
end;
$$;

revoke all on function public.list_privileged_audit_events(integer, timestamptz) from public, anon;
grant execute on function public.list_privileged_audit_events(integer, timestamptz) to authenticated;

commit;
